### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by Jianhui-Li** [intel/mlir-extensions#209]
This intel mlir extensions (imex) repo is created to help reuse MLIR infrastructure and promote collaboration, so we would like to keep all dialects inside the "mlir" directory and follow a similar structure as upstream llvm/mlir directory structure.  

Please consider the following code refactoring. 
1. Plier dialect fully move to "mlir" directory.  The plier conversion to Linalg/scf/ should move to "mlir" directory.  In general, mlir/lib/converter should be organized as upstream – each converter lives inside a subdirectory.  
2. Plier conversion to linalg/std should not know Numba construct (PyFunc). The goal is that imex dialects should not know about upper level SW construct. 
3. Dpcomp_gpu_Runtime should merge into coming mlir/lib/dialect/intel_gpu
4. Dpcomp_runtime needs some more analysis
5. Test and tools should move inside mlir, Tools/Dpcomp-opt should be renamed as imex-opt

**Comment by Jianhui-Li** [comment]
@silee2  @diptorupd

**Comment by fschlimb** [comment]
We also need a tools/util directory for common (non-python) things like casting etc. This should not live in anything with "plier" in its name.

**Comment by fschlimb** [comment]
@diptorupd I created a new branch for refactoring everything from scratch: https://github.com/intel/mlir-extensions/tree/refactor
It has only a rudimentary readme and it does not do anything real yet. I even get compile issues I never got before. Investigating.

**Comment by diptorupd** [comment]
@Jianhui-Li @silee2 @nbpatel I propose making the refactor branch main and archiving the current main. I will convert existing Plier dialect to a new NumbaIR dialect and move things slowly over to the new branch. 

I suggest we do the same for GPU_runtime and redesign it like upstreams NVGPU dialect. I am willing to help.

Having tired to clean up and refactor existing main over past month, I strongly feel that going @fschlimb route of clean house reimplementation makes sense.

**Comment by Hardcode84** [comment]
> I propose making the refactor branch main and archiving the current main.

I'm strongly against it. It will make main branch non-functional for months given the current scarce resources and I don't see any reason why it cannot be done incrementally.
