### ISSUE TITLE
IMEX needs a CLI tool similar to mlir-opt

### ISSUE THREAD

**Issue by diptorupd** [intel/mlir-extensions#233]
The `mlir-opt` tool makes it easy to run any MLIR pass using a default global registry. The tool is useful to design `FileCheck` test cases.

IMEX needs a similar tool. The following pieces need to be put in place before the tool can be put together:

- [x] Add a `Passes.td` and `Passes.h` to our `Conversion` folder. These two files are provided by the MLIR repo and are used to define the registration functions for all `Conversion` passes.
- [x] Add `Passes.td` and `Passes.h` to all IMEX `Dialect` that define passes.
- [x] Add an `InitIMEXDialects.h` header similar to the `InitAllDialects.h` in MLIR.
- [x] Add an `InitIMEXPasses.h` header similar to `InitAllPasses.h` in MLIR.
- [x] Add an `imex-opt.cpp` source similar to `mlir-opt.cpp`

Explore automation possibilities to auto-generate these files as most of the files will need mechanical maintenance.

PS: The automation scripts in our repo are `meta^2` programming. Use Python to generate TableGen that then generates C++. Ergo, Python rules them all!!

**Comment by silee2** [comment]
I was thinking about doing the same thing at some point. Thanks for starting the effort.

**Comment by diptorupd** [comment]
The tool is now available in `refactor` branch.
