### ISSUE TITLE
Remove broken Azure CI

### ISSUE THREAD

**Issue by diptorupd** [intel/mlir-extensions#256]
The Azure CI has been broken for a while. There is no plans to revive it and the team is moving to a better CI solution. Can the CI checks be removed?

**Comment by silee2** [comment]
Not sure how to remove it. I'll do a quick web search if there is an easy way to disable/remove azure ci.

**Comment by silee2** [comment]
I couldn't remove Azure CI entirely but found a way to disable triggering it.
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml
Azure CI should not trigger anymore.
