### ISSUE TITLE
Rename main to numba-dev and refactor to main

### ISSUE THREAD

**Issue by silee2** [intel/mlir-extensions#551]
Steps for renaming

Step 0: prepare
// pull the latest code to local
git fetch origin

Step 1: create numba-dev from old main
// create a new branch from the existing main branch
git checkout -b numba-dev origin/main
// push the new branch back to github. This will need write access to the github repo.
git push origin numba-dev

Step 2: create and push new main from refactor
// rename the existing main
git branch -m main ex-main
// checkout a new main at local from the refactor branch
git checkout -b main origin/refactor
// update README.md replace refactor with main
// push the new main to github. As git-history is written, force push is needed (-f in the command line). Also write access is needed and the github main branch should not be protected.
git push origin main -f
// done and check the github webpage for the new branches.

**Comment by fschlimb** [comment]
If there are no objections I’d like to merge my latest ptensor stuff into refactor before the change (#389).
We can discuss how to deal with ptensor/dist in the future, but I’d like to minimize possible quirks now and in future due to renaming.

**Comment by silee2** [comment]
Renaming is complete.
