### ISSUE TITLE
Add external call capability in SPIRV dialect

### ISSUE THREAD

**Issue by chengjunlu** [intel/mlir-extensions#636]
We need the external call capability in SPIRV dialect to call external library for the SPIRV kernel.

This is a Triton requirements memo.

**Comment by mshahneo** [comment]
The PR is going through the upstream process now: https://reviews.llvm.org/D148749

**Comment by EikanWang** [comment]
According to the review comments, I suppose there is no blocking issue, right? If yes, @mshahneo , cold you predict the ETA to be landed?

**Comment by mshahneo** [comment]
Hi All,

The PR got merged.
https://reviews.llvm.org/D148749

Closing the issue.
