### ISSUE TITLE
To support printf in SPIRV dialect which could be landing to the OCL printf.

### ISSUE THREAD

**Issue by chengjunlu** [intel/mlir-extensions#643]
To support printf in SPIRV dialect which could be landing to the OCL printf.

**Comment by drprajap** [comment]
Patch with PrintfOp support in SPIRV Dialect has been accepted and merge upstream - https://reviews.llvm.org/D151731, LLVM revision - [8939b5f](https://github.com/llvm/llvm-project/commit/8939b5f5d2f30186a72f4ad44480ee9978663998)
