### ISSUE TITLE
Enhance the CompositeExtractOp fold like LLVM ExtractValueOp.

### ISSUE THREAD

**Issue by chengjunlu** [intel/mlir-extensions#648]
In the Triton lowering, we would have such kind of logic for the composing data.

```
  %183 = spirv.CompositeInsert %179, %144[0 : i32] : f32 into !spirv.struct<(f32, f32)>
    %184 = spirv.CompositeInsert %182, %183[1 : i32] : f32 into !spirv.struct<(f32, f32)>
    %185 = spirv.CompositeExtract %184[0 : i32] : !spirv.struct<(f32, f32)>
```
It `%185` could be optimized that fold the composite inster/extract with the origin value `%179`. 

Like the LLVM dialect ExtractValueOp: https://github.com/llvm/llvm-project/blob/fa1f88cdeca245497843c507167b84f5522e88cc/mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp#L1423

**Comment by nbpatel** [comment]
This is already done in upstream here
https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SPIRV/IR/SPIRVCanonicalization.cpp#L143

**Comment by nbpatel** [comment]
PR merged upstream 
https://reviews.llvm.org/D151536
