### ISSUE TITLE
MathToSPIRV missed math::AbsIop to spirv::CLSAbsOp conversion. 

### ISSUE THREAD

**Issue by chengjunlu** [intel/mlir-extensions#650]
Public MLIR MathToSPIRV missed this conversion:
https://github.com/chengjunlu/llvm/blob/5bea8d7359c8b0805b031fd6c4e596575b604ffa/mlir/lib/Conversion/MathToSPIRV/MathToSPIRV.cpp#LL397C40-L397C40

**Comment by nbpatel** [comment]
This change got merged upstream 
https://reviews.llvm.org/D151378
